// Dumps every row of `articles` out of the ORPHANED Supabase project, and
// derives the CREATE TABLE statement from the data.
//
// Context: project wvuydfupjpjmanqccdax is not reachable from any Supabase
// account we can sign into, so its leaked anon key can never be rotated. The
// only way to close that exposure is to stop using the project. Read access
// still works, so the content comes out first.
//
//   railway run node scripts/migrate-dump.mjs

import { writeFileSync } from 'node:fs';

const URL_BASE = process.env.SUPABASE_URL;
const KEY = process.env.SUPABASE_KEY;
if (!URL_BASE || !KEY) { console.error('Missing SUPABASE_URL / SUPABASE_KEY'); process.exit(1); }
const H = { apikey: KEY, Authorization: `Bearer ${KEY}` };

const rows = [];
for (let from = 0; ; from += 1000) {
  const r = await fetch(`${URL_BASE}/rest/v1/articles?select=*&order=id.asc&limit=1000&offset=${from}`, { headers: H });
  if (!r.ok) { console.error(`Supabase ${r.status}: ${(await r.text()).slice(0,300)}`); process.exit(1); }
  const batch = await r.json();
  rows.push(...batch);
  process.stdout.write(`\rfetched ${rows.length}`);
  if (batch.length < 1000) break;
}
console.log(`\nTOTAL: ${rows.length} rows`);

// Infer a column type from the values actually present.
const cols = new Map();
for (const row of rows) {
  for (const [k, v] of Object.entries(row)) {
    const cur = cols.get(k) || { types: new Set(), maxLen: 0, nulls: false };
    if (v === null || v === undefined) cur.nulls = true;
    else {
      cur.types.add(typeof v);
      if (typeof v === 'string') cur.maxLen = Math.max(cur.maxLen, v.length);
    }
    cols.set(k, cur);
  }
}

const sqlType = (name, info) => {
  if (name === 'id') return 'bigint generated by default as identity primary key';
  if (info.types.has('number')) return 'bigint';
  if (info.types.has('boolean')) return 'boolean';
  if (/_at$/.test(name)) return 'timestamptz';
  return 'text';
};

const lines = [...cols].map(([n, i]) => `  ${n} ${sqlType(n, i)}${n !== 'id' && !i.nulls ? ' not null' : ''}`);
const ddl = `create table public.articles (\n${lines.join(',\n')}\n);

create unique index articles_slug_key on public.articles (slug);
create index articles_published_at_idx on public.articles (published_at desc);
create index articles_region_idx on public.articles (region);

-- The old project let the anon role INSERT, which is why a leaked anon key was
-- a write credential. Here anon is read-only and the generator uses service_role.
alter table public.articles enable row level security;

create policy "public read" on public.articles
  for select to anon, authenticated using (true);
`;

writeFileSync('articles-dump.json', JSON.stringify(rows));
writeFileSync('articles-schema.sql', ddl);
console.log(`\nwrote articles-dump.json (${rows.length} rows)`);
console.log('wrote articles-schema.sql');
console.log('\ncolumns:', [...cols.keys()].join(', '));
